"""typo fixed

Revision ID: 76ca88e61336
Revises: 7c181ff0e23f
Create Date: 2025-12-14 11:58:44.908773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ca88e61336'
down_revision: Union[str, Sequence[str], None] = '7c181ff0e23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_column('User', 'hasshed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('hasshed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('User', 'hashed_password')
    # ### end Alembic commands ###
