"""user db v2

Revision ID: 7c181ff0e23f
Revises: 944985b086bd
Create Date: 2025-12-13 19:17:34.350880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c181ff0e23f'
down_revision: Union[str, Sequence[str], None] = '944985b086bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('hasshed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'hasshed_password')
    # ### end Alembic commands ###
