"""created_at added to user model

Revision ID: bb5b23765eb6
Revises: 76ca88e61336
Create Date: 2025-12-15 11:30:34.524225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5b23765eb6'
down_revision: Union[str, Sequence[str], None] = '76ca88e61336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('User', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('User', 'created_at')
    # ### end Alembic commands ###
